services:
  metube:
    image: alexta69/metube
    container_name: metube
    ports:
      - "8081:8081"
    volumes:
      - /data/downloads:/downloads
    environment:
      - UID=1000
      - GID=1000
    restart: unless-stopped