services:
  hawser:
    container_name: hawser
    image: ghcr.io/finsys/hawser:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - hawser-stacks:/opt/hawser-stacks
    ports:
      - 2376:2376
