services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: always
    ports:
      - "$UPTIME_KUMA_HOST_PORT:3001"  # This maps the container port "3001" to the host port "3001"
    volumes:
      - uptime-kuma_data:/app/data  # Configuring persistent storage
      - /var/run/docker.sock:/var/run/docker.sock # Mount the Docker socket
    environment:
      - TZ=$UPTIME_KUMA_TZ  # Set the timezone (change to your preferred local timezone so monitoring times are the same)
      - UMASK=0022  # Set your file permissions manually
    networks:
      - kuma_network  # add your own custom network config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  uptime-kuma_data:
    name: uptime-kuma_data

networks:
  kuma_network:
    driver: bridge
