services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # Number of GPUs to use
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  ollama:
    name: ollama
    